title: UnsaidPages
description: "Stories that were felt, not just written."
baseurl: ""
url: "https://unsaidpages.zippedhost.dpdns.org"
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
