title: UnsaidPages
description: "Stories that were felt, not just written."
baseurl: "/UnsaidPages"
url: "https://gamercr4cked.github.io"
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
