title: UnsaidPages
description: "Stories that were felt, not just written."
baseurl: ""
url: "https://gamercr4cked.github.io/UnsaidPages/"
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
